# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rowmeans cpp function
#'
#' @param X a matrix
#' @export
arma_rowMeans <- function(X) {
    .Call(`_covcpd_arma_rowMeans`, X)
}

#' colmeans cpp function
#'
#' @param X a matrix.
#' @export
arma_colMeans <- function(X) {
    .Call(`_covcpd_arma_colMeans`, X)
}

#' calculate the Mn statistic from Cai et al. (2013)
#'
#' @param X samples by covariates (genes)
#' @param Y samples by covariates (genes)
#' @param alpha significance level
#' @export
testCov_cpp <- function(X, Y, alpha = 0.05) {
    .Call(`_covcpd_testCov_cpp`, X, Y, alpha)
}

#' Permutation to learn data-specific Gumbel distribution parameters
#'
#' @param X: samples by covariates (genes)
#' @param searchx: candidate change point locations that will be tested.
#' @param start: the start location of the current segment
#' @param nperm: number of permutations
#' @export
CLXstatPerm <- function(X, searchx, start, nperm) {
    .Call(`_covcpd_CLXstatPerm`, X, searchx, start, nperm)
}

calc_ranks <- function(da_ta) {
    .Call(`_covcpd_calc_ranks`, da_ta)
}

#' Hierarchical Permutation to learn data-specific Gumbel distribution parameters
#'
#' @param X: samples by covariates (genes)
#' @param searchx: candidate change point locations that will be tested.
#' @param start: the start location of the current segment
#' @param nperm: number of permutations
#' @param nt2: number of varied segment 2. Default is 4, which means we fix the length of segment 1 and vary the length of segment 2 for 4 times. The lengths for the varied segment 2s are equally spaced.
#' @param minband: minimum bandwidth of a segment. Default is 20.
#' @export
CLXPermHier <- function(X, searchx, start, nt2 = 4L, minband = 20L, nperm = 100L) {
    .Call(`_covcpd_CLXPermHier`, X, searchx, start, nt2, minband, nperm)
}

myQnorm <- function(mp) {
    .Call(`_covcpd_myQnorm`, mp)
}

getMatNPN <- function(input, N) {
    .Call(`_covcpd_getMatNPN`, input, N)
}

